### PR TITLE
Update plotly kaleido

### PR DESCRIPTION
**Pull request by ParthivNaresh**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Updates plotly version to 4.14.1 to support kaleido 0.1.0

### CODE REVIEW

**Comment by freddyaboulton** [comment]
@jonmmease we're trying to make python-kaleido as dependency but were getting a noarch error from fontconfig. Any idea how we can fix this?  

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=253794&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

**Comment by jonmmease** [comment]
Hi @freddyaboulton.

One idea. The linux-64 build of the `kaleido-core` conda package (which the noarch `python-kaleido` depends on) requires CentOS 7+.  For CI on conde-forge, this is done in `conda_build_config.yaml` by setting the `docker_image` to `condaforge/linux-anvil-cos7-x86_64`.

It doesn't make sense to me that conda would ultimately complain about `fontconfig` here, but conda reporting on package conflicts is mysterious sometimes, so I think it's worth a try.

This also means that if you need your package to work on CentOS 6, you shouldn't add a hard dependency on `python-kaleido` (at least until conda-forge drops CentOS 6 support).

**Comment by freddyaboulton** [comment]
@jonmmease Yes, changing the docker image fixed our CI woes. Thank you so much for the help! We really appreciate it :) 

It might be helpful to add the tip about building on CentOS 7+ to the python-kaleido feedstock? We would have really struggled to figure this out without your help! 

Thanks again! 🚀

**Comment by jonmmease** [comment]
> It might be helpful to add the tip about building on CentOS 7+ to the python-kaleido feedstock? We would have really struggled to figure this out without your help!

Yeah, that's a good point.  Unfortunately it's going to be a viral requirement for anything that depends on `kaleido-core`, including this package.

Glad it's working for you!

**Review by freddyaboulton — APPROVED** [review]
Looks good to me @ParthivNaresh !

**Pull request merged**
